[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_faster = 1
    let g:indentLine_enabled = 1
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
	nmap j <Plug>(accelerated_jk_gj)
	nmap k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	nmap <silent><C-n> :NERDTreeToggle<CR>
'''
